### ISSUE TITLE
There was an error in your GraphQL query: ETIMEDOUT

### ISSUE THREAD

**Issue by socmov** [rshackleton/gatsby-transformer-kontent-image#22]
I'm using this with the latest version of gatsby-source-kontent (v5.0.0) which has made a few breaking changes to fix a bug (https://github.com/Kentico/gatsby-source-kontent/issues/110)

Whenever I try to run fluid or fixed I get an error: ETIMEDOUT. I'm not sure if it is related to the new kontent source changes or something else. 
```
background_image {
  value {
    url
    fluid(maxWidth: 1920) {
       ...KontentAssetFluid
     }
  }
}
```

**Comment by socmov** [comment]
Actually - this happens when you have some records with a value and some records without - it times outs on the records that don't have a value. It doesn't cause the build to fail but I assume it is delaying the build by waiting for the timeouts.

**Comment by rshackleton** [comment]
@socmov thanks for logging this, I've [moved the repo](https://github.com/rshackleton/gatsby-packages/tree/master/packages/gatsby-transformer-kontent-image) so would you be able to log the issue there?
